# Generated by Django 4.0 on 2022-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.BigIntegerField()),
                ('code', models.CharField(max_length=12)),
                ('origin', models.CharField(max_length=10)),
                ('property', models.CharField(max_length=120)),
                ('property_code', models.CharField(max_length=50)),
                ('arrival', models.DateField(auto_now=True)),
                ('departure', models.DateField(auto_now=True)),
                ('accomodation', models.CharField(max_length=100)),
                ('reservation_holder', models.CharField(max_length=60)),
                ('reservation_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('currency', models.CharField(max_length=7)),
                ('payment_method', models.CharField(choices=[('bank', 'bank'), ('cc', 'cc'), ('fax', 'fax')], max_length=10)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('OK', 'OK'), ('On hold', 'On hold')], max_length=10)),
                ('date_of_creation', models.DateField(auto_now=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('language', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('ES', 'ES'), ('FI', 'FI'), ('FR', 'FR'), ('HU', 'HU'), ('IT', 'IT'), ('NL', 'NL'), ('PL', 'PL'), ('RU', 'RU')], max_length=5)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('access_code', models.CharField(blank=True, max_length=10, null=True)),
                ('b2b_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('rooming_info', models.TextField(blank=True, max_length=300, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('rate_plan_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Booking Data',
                'verbose_name_plural': 'Booking Data',
                'db_table': 'booking_data',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'upload_data',
            },
        ),
    ]
