# Generated by Django 4.0 on 2022-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.BigIntegerField(verbose_name='booking_id')),
                ('code', models.CharField(max_length=12, verbose_name='code')),
                ('origin', models.CharField(max_length=10, verbose_name='origin')),
                ('property', models.CharField(max_length=120, verbose_name='property')),
                ('property_code', models.CharField(max_length=50, verbose_name='property_code')),
                ('arrival', models.DateField(verbose_name='arrival')),
                ('departure', models.DateField(verbose_name='departure')),
                ('accomodation', models.CharField(max_length=100, verbose_name='accomodation')),
                ('reservation_holder', models.CharField(max_length=60, verbose_name='reservation_holder')),
                ('reservation_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='reservation_total')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='tax')),
                ('currency', models.CharField(max_length=7, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('bank', 'bank'), ('cc', 'cc'), ('fax', 'fax')], max_length=10, verbose_name='payment_method')),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('OK', 'OK'), ('On hold', 'On hold')], max_length=10, verbose_name='status')),
                ('date_of_creation', models.DateField(verbose_name='date_of_creation')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('country', models.CharField(blank=True, choices=[('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Hungary', 'Hungary'), ('Italy', 'Italy'), ('Latvia', 'Latvia'), ('Netherlands', 'Netherlands'), ('Poland', 'Poland'), ('Romania', 'Romania'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('United Kingdom', 'United Kingdom')], max_length=25, null=True, verbose_name='country')),
                ('language', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('ES', 'ES'), ('FI', 'FI'), ('FR', 'FR'), ('HU', 'HU'), ('IT', 'IT'), ('NL', 'NL'), ('PL', 'PL'), ('RU', 'RU')], max_length=5, verbose_name='language')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='zipcode')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('access_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='access_code')),
                ('b2b_discount', models.CharField(blank=True, max_length=10, null=True, verbose_name='b2b_discount')),
                ('rooming_info', models.TextField(blank=True, max_length=300, null=True, verbose_name='rooming_info')),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='deposit')),
                ('rate_plan_name', models.CharField(max_length=100, verbose_name='rate_plan_name')),
            ],
            options={
                'verbose_name': 'Booking Data',
                'verbose_name_plural': 'Booking Data',
                'db_table': 'booking_data',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parse_type', models.CharField(choices=[('Parse Normally', 'Parse Normally'), ('Parse with pandas', 'Parse with pandas')], default='Parse Normally', max_length=20)),
            ],
            options={
                'db_table': 'upload_data',
            },
        ),
    ]
