# Generated by Django 4.0 on 2022-01-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='access_code'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='accomodation',
            field=models.CharField(max_length=100, verbose_name='accomodation'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='arrival',
            field=models.DateField(auto_now=True, verbose_name='arrival'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='b2b_discount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='b2b_discount'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='booking_id',
            field=models.BigIntegerField(verbose_name='booking_id'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='code',
            field=models.CharField(max_length=12, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='currency',
            field=models.CharField(max_length=7, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='date_of_creation',
            field=models.DateField(auto_now=True, verbose_name='date_of_creation'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='departure',
            field=models.DateField(auto_now=True, verbose_name='departure'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='deposit'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='email',
            field=models.CharField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='language',
            field=models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('ES', 'ES'), ('FI', 'FI'), ('FR', 'FR'), ('HU', 'HU'), ('IT', 'IT'), ('NL', 'NL'), ('PL', 'PL'), ('RU', 'RU')], max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='origin',
            field=models.CharField(max_length=10, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'bank'), ('cc', 'cc'), ('fax', 'fax')], max_length=10, verbose_name='payment_method'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='property',
            field=models.CharField(max_length=120, verbose_name='property'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='property_code',
            field=models.CharField(max_length=50, verbose_name='property_code'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='rate_plan_name',
            field=models.CharField(max_length=100, verbose_name='rate_plan_name'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='reservation_holder',
            field=models.CharField(max_length=60, verbose_name='reservation_holder'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='reservation_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='reservation_total'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='rooming_info',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='rooming_info'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('OK', 'OK'), ('On hold', 'On hold')], max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='zipcode'),
        ),
    ]
