# Generated by Django 4.0 on 2022-01-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
